[project]
name = "genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gensim>=4.4.0",
    "nltk>=3.9.2",
    "pypdf[image]>=6.4.0",
    "scikit-learn>=1.7.2",
    "spacy>=3.8.11",
]
